from PyQt6 import QtCore, QtGui, QtWidgets
import requests
import datetime

BASE_URL = "https://api.waktusolat.app/v2/solat/"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 527)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_tarikh = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tarikh.setFont(font)
        self.label_tarikh.setObjectName("label_tarikh")
        self.horizontalLayout_3.addWidget(self.label_tarikh)
        self.tarikh = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tarikh.setFont(font)
        self.tarikh.setObjectName("tarikh")
        self.horizontalLayout_3.addWidget(self.tarikh)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_waktu_solat_next = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_waktu_solat_next.setFont(font)
        self.label_waktu_solat_next.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_waktu_solat_next.setObjectName("label_waktu_solat_next")
        self.verticalLayout_2.addWidget(self.label_waktu_solat_next)
        self.time_waktu_solat_next = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_waktu_solat_next.setFont(font)
        self.time_waktu_solat_next.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_waktu_solat_next.setObjectName("time_waktu_solat_next")
        self.verticalLayout_2.addWidget(self.time_waktu_solat_next)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_subuh = QtWidgets.QVBoxLayout()
        self.frame_subuh.setObjectName("frame_subuh")
        self.label_subuh = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_subuh.setFont(font)
        self.label_subuh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_subuh.setObjectName("label_subuh")
        self.frame_subuh.addWidget(self.label_subuh)
        self.time_subuh = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_subuh.setFont(font)
        self.time_subuh.setMouseTracking(False)
        self.time_subuh.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.time_subuh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_subuh.setObjectName("time_subuh")
        self.frame_subuh.addWidget(self.time_subuh)
        self.horizontalLayout.addLayout(self.frame_subuh)
        self.frame_syuruk = QtWidgets.QVBoxLayout()
        self.frame_syuruk.setObjectName("frame_syuruk")
        self.label_syuruk = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_syuruk.setFont(font)
        self.label_syuruk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_syuruk.setObjectName("label_syuruk")
        self.frame_syuruk.addWidget(self.label_syuruk)
        self.time_syuruk = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_syuruk.setFont(font)
        self.time_syuruk.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_syuruk.setObjectName("time_syuruk")
        self.frame_syuruk.addWidget(self.time_syuruk)
        self.horizontalLayout.addLayout(self.frame_syuruk)
        self.frame_zohor = QtWidgets.QVBoxLayout()
        self.frame_zohor.setObjectName("frame_zohor")
        self.label_zohor = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_zohor.setFont(font)
        self.label_zohor.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_zohor.setObjectName("label_zohor")
        self.frame_zohor.addWidget(self.label_zohor)
        self.time_zohor = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_zohor.setFont(font)
        self.time_zohor.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_zohor.setObjectName("time_zohor")
        self.frame_zohor.addWidget(self.time_zohor)
        self.horizontalLayout.addLayout(self.frame_zohor)
        self.frame_asar = QtWidgets.QVBoxLayout()
        self.frame_asar.setObjectName("frame_asar")
        self.label_asar = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label_asar.setFont(font)
        self.label_asar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_asar.setObjectName("label_asar")
        self.frame_asar.addWidget(self.label_asar)
        self.time_asar = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_asar.setFont(font)
        self.time_asar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_asar.setObjectName("time_asar")
        self.frame_asar.addWidget(self.time_asar)
        self.horizontalLayout.addLayout(self.frame_asar)
        self.frame_maghrib = QtWidgets.QVBoxLayout()
        self.frame_maghrib.setObjectName("frame_maghrib")
        self.label_maghrib = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_maghrib.setFont(font)
        self.label_maghrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_maghrib.setObjectName("label_maghrib")
        self.frame_maghrib.addWidget(self.label_maghrib)
        self.time_maghrib = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_maghrib.setFont(font)
        self.time_maghrib.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_maghrib.setObjectName("time_maghrib")
        self.frame_maghrib.addWidget(self.time_maghrib)
        self.horizontalLayout.addLayout(self.frame_maghrib)
        self.frame_isyak = QtWidgets.QVBoxLayout()
        self.frame_isyak.setObjectName("frame_isyak")
        self.label_isyak = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_isyak.setFont(font)
        self.label_isyak.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_isyak.setObjectName("label_isyak")
        self.frame_isyak.addWidget(self.label_isyak)
        self.time_isyak = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.time_isyak.setFont(font)
        self.time_isyak.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_isyak.setObjectName("time_isyak")
        self.frame_isyak.addWidget(self.time_isyak)
        self.horizontalLayout.addLayout(self.frame_isyak)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.get_waktu('SGR01')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_tarikh.setText(_translate("MainWindow", "Tarikh Masa"))
        self.tarikh.setText(_translate("MainWindow", "DD/MM/YYYY HH:MM:ss"))
        self.label.setText(_translate("MainWindow", "Waktu solat seterusnya:"))
        self.label_waktu_solat_next.setText(_translate("MainWindow", "waktu_solat"))
        self.time_waktu_solat_next.setText(_translate("MainWindow", "00:00"))
        self.label_subuh.setText(_translate("MainWindow", "Subuh"))
        self.time_subuh.setText(_translate("MainWindow", "00:00"))
        self.label_syuruk.setText(_translate("MainWindow", "Syuruk"))
        self.time_syuruk.setText(_translate("MainWindow", "00:00"))
        self.label_zohor.setText(_translate("MainWindow", "Zohor"))
        self.time_zohor.setText(_translate("MainWindow", "00:00"))
        self.label_asar.setText(_translate("MainWindow", "Asar"))
        self.time_asar.setText(_translate("MainWindow", "00:00"))
        self.label_maghrib.setText(_translate("MainWindow", "Maghrib"))
        self.time_maghrib.setText(_translate("MainWindow", "00:00"))
        self.label_isyak.setText(_translate("MainWindow", "Isyak"))
        self.time_isyak.setText(_translate("MainWindow", "00:00"))

    def get_waktu(self, zone):
        today = datetime.datetime.today()
        self.tarikh.setText(today.strftime("%d/%m/%Y %H:%M:%S"))
        response = requests.get(f'{BASE_URL}{zone}')
        if response.status_code != 200:
            return
        prayer_index = today.day - 1
        response_dict = response.json()
        self.time_subuh.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['fajr']).strftime("%H:%M")))
        self.time_syuruk.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['syuruk']).strftime("%H:%M")))
        self.time_zohor.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['dhuhr']).strftime("%H:%M")))
        self.time_asar.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['asr']).strftime("%H:%M")))
        self.time_maghrib.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['maghrib']).strftime("%H:%M")))
        self.time_isyak.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['isha']).strftime("%H:%M")))
        if int(today.timestamp()) < response_dict['prayers'][prayer_index]['syuruk']:
            self.label_waktu_solat_next.setText("Syuruk")
            self.time_waktu_solat_next.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['syuruk']).strftime("%H:%M")))
        elif int(today.timestamp()) < response_dict['prayers'][prayer_index]['dhuhr']:
            self.label_waktu_solat_next.setText("Zohor")
            self.time_waktu_solat_next.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['dhuhr']).strftime("%H:%M")))
        elif int(today.timestamp()) < response_dict['prayers'][prayer_index]['asr']:
            self.label_waktu_solat_next.setText("Asar")
            self.time_waktu_solat_next.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['asr']).strftime("%H:%M")))
        elif int(today.timestamp()) < response_dict['prayers'][prayer_index]['maghrib']:
            self.label_waktu_solat_next.setText("Maghrib")
            self.time_waktu_solat_next.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['maghrib']).strftime("%H:%M")))
        elif int(today.timestamp()) < response_dict['prayers'][prayer_index]['isha']:
            self.label_waktu_solat_next.setText("Isyak")
            self.time_waktu_solat_next.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['isha']).strftime("%H:%M")))
        else:
            self.label_waktu_solat_next.setText("Subuh")
            self.time_waktu_solat_next.setText(str(datetime.datetime.fromtimestamp(response_dict['prayers'][prayer_index]['fajr']).strftime("%H:%M")))            
        # print(response_dict['prayers'][prayer_index])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
